# Generated by Django 4.2.6 on 2023-11-05 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_request_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
